theme = "awesome-identity"
baseURL = ""
relativeURLs = "True"
uglyURLs = true
canonifyURLs = true

## Profile Configurations
[params.profile]
  portrait = "/images/vik.jpg"
  firstname = "Vikrant"
  lastname = "Biswas"
  title = "Software Engineer"
  bio = """Currently Software Engineer at Unified Communication company Mitel Networks. 5+ years of experience specializing in Full Stack Development, Test Automation, and System Administration. Interested in devising a better problem-solving method for challenging tasks, and learning new technologies and tools if the need arises.
  """
[params.contacts]
  email = "vikrant.biswas@gmail.com"
  github = "windlessstorm"
  linkedin = "vikrantb"

## Actions Configurations
[[params.actions]]
  name = "Review My CV"
  url = "https://windlessstorm.github.io/resume/resume.pdf"
[[params.actions]]
  name = "Buy Me a Coffee"
  url = "https://buymeacoff.ee/vikrantb"


## Footer Configurations
[params.footer]
  copyright = "© 2022-2023 Vikrant Biswas. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true