theme = "awesome-identity"
baseURL = ""


## Profile Configurations
[params.profile]
  portrait = "https://i.imgur.com/qbW3Ux6.jpg"
  firstname = "Vikrant"
  lastname = "Biswas"
  title = "Software Engineer"
  bio = """Software engineer experienced in web services and distributed systems looking forward to building highly available, 
  scalable, and testable software products.
  """
[params.contacts]
  email = "vikrant.biswas@gmail.com"
  github = "windlessstorm"
  linkedin = "vikrantb"

## Actions Configurations
[[params.actions]]
  name = "Review My CV"
  url = "https://windlessstorm.github.io/resume/my_resume.pdf"
[[params.actions]]
  name = "Buy Me a Coffee"
  url = "https://buymeacoff.ee/vikrantb"


## Footer Configurations
[params.footer]
  copyright = "© 2022-2023 Vikrant Biswas. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true